---
latitude: 
longitude: 
map_zoom: 12
name: 
email: 
phone_number: 
address: 
_hotel_id: HOT144
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
